language: cpp
dist: bionic

compiler:
  - clang
  - gcc

env:
  - BUILD_VARIANT=Debug
  - BUILD_VARIANT=Release

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.12.6-bionic'
    packages:
      - wget
      - make
      - libssl-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - gcc-8
      - g++-8
      - clang-8
      - qt512base
      - qt512declarative
      - qt512multimedia
      - qt512quickcontrols2

before_install:
  # - |
  #   travis_retry wget -q https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
  #   sh cmake-3.12.3-Linux-x86_64.sh --skip-license
  # - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - export RC_PARAMS="max_success=800 max_size=200"

script:
  - if [ "$TRAVIS_COMPILER" == "gcc" ]; then export CXX=g++-8; export CC=gcc-8; fi
  - if [ "$TRAVIS_COMPILER" == "clang" ]; then export CXX=clang++-8; export CC=clang-8; fi
  - source /opt/qt512/bin/qt512-env.sh
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=$BUILD_VARIANT -DCMAKE_INSTALL_PREFIX:STRING=$TRAVIS_BUILD_DIR/install
  - cmake --build .
  - cmake --build . --target install
  - ls -lahR $TRAVIS_BUILD_DIR/install
  - cd tests && ctest -V
